# Generated by Django 4.2.7 on 2023-11-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strenght",
            fields=[
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("melee_attack", models.SmallIntegerField()),
                ("damage", models.SmallIntegerField()),
                ("non_encum", models.PositiveSmallIntegerField()),
                ("max_weight", models.PositiveSmallIntegerField()),
                ("force_doors", models.PositiveSmallIntegerField()),
                ("force_locked", models.PositiveSmallIntegerField(blank=True)),
                ("bend_bars", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
