# Generated by Django 4.2.7 on 2023-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strenght",
            name="force_locked",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
