# Generated by Django 4.2.7 on 2023-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_alter_strenght_force_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="strenght",
            name="exceptional_strenght",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
