# Generated by Django 4.2.7 on 2023-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0005_strenght_exceptional_strenght"),
    ]

    operations = [
        migrations.RenameField(
            model_name="strenght",
            old_name="exceptional_strenght",
            new_name="exceptional",
        ),
        migrations.AddField(
            model_name="strenght",
            name="id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="strenght",
            name="score",
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
