# Generated by Django 4.2.7 on 2023-11-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0006_rename_exceptional_strenght_strenght_exceptional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strenght",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="strenght",
            unique_together={("score", "exceptional")},
        ),
    ]
