# Generated by Django 4.2.7 on 2023-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0007_alter_strenght_id_alter_strenght_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strenght",
            name="score",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
